### PR TITLE
Try to fix ctrl-c

### PR DESCRIPTION
**Pull request by jtojnar**
See #64

### CODE REVIEW

**Comment by jtojnar** [comment]
It is pretty verbose and I am not sure it handles every case. Maybe some GTK guru could suggest a better way.

**Comment by jtojnar** [comment]
And it still does not work. Just saving colour will trigger `gcolor3_window_selection_changed` activating the copy action.

**Comment by jtojnar** [comment]
Also I am not sure, when I start editing the name of a colour and then click the Picker tab, if `gcolor3_window_color_editing_canceled` always triggers before `gcolor3_window_stack_changed`?

**Comment by jtojnar** [comment]
Superseded by https://github.com/Hjdskes/gcolor3/pull/92

**Comment by Hjdskes** [comment]
Thanks for your help!

**Pull request closed without merging**
