### PR TITLE
Greek translation update

### PR DESCRIPTION
**Pull request by subdee**

### CODE REVIEW

**Comment by Hjdskes** [comment]
Please see the instructions in the README on how to update a translation.

**Comment by subdee** [comment]
Indeed, I will reopen when finished.

**Comment by Hjdskes** [comment]
You don't need to close this. Just push your changes to the same branch and it will update.

**Comment by Hjdskes** [comment]
Closing this as Gcolor3 has moved to GNOME GitLab, where it will now be translated by GNOME's translation teams.

**Pull request closed without merging**
