### PR TITLE
[Translate] Add Indonesian translation

### PR DESCRIPTION
**Pull request by dindinG41TR3**
Add Indonesian translation

### CODE REVIEW

**Comment by Hjdskes** [comment]
Can you add an entry to the [`LINGUAS`](https://github.com/Hjdskes/gcolor3/blob/master/po/LINGUAS) file as described in the README?

**Comment by dindinG41TR3** [comment]
Ok

**Comment by Hjdskes** [comment]
Thanks!

**Comment by dindinG41TR3** [comment]
You are welcome

**Pull request merged**
